"""Tests para ISSUE-002: parse_response debe usar el $ref de la respuesta, no el schema por método.

Bug: get_schema_definition_by_model_and_method busca por x-apigen-mapping.method,
lo que para POST devuelve PetPost. Pero el responses.200 apunta a PetGet.
El response_schema_name debe ser PetGet para POST addPet.
"""
import pytest
from src.domain.parse_core.parsers.openapi_parser import OpenAPIParser


# Spec donde POST /pet responde con PetGet (no PetPost)
RESPONSE_SCHEMA_SPEC = """
openapi: 3.0.4
info:
  title: test-response-schema
  version: 1.0.0
x-apigen-project:
  name: test-response-schema
  description: test
  version: v1.0.0
  data-driver: postgresql
paths:
  /pet:
    x-apigen-binding:
      model: Pet
    get:
      operationId: listPets
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PetGet'
    post:
      operationId: addPet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetPost'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetGet'
    put:
      operationId: updatePet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetPut'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetGet'
  /pet/{petId}:
    x-apigen-binding:
      model: Pet
      petId: Pet.id
    get:
      operationId: getPetById
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetGet'
components:
  x-apigen-models:
    Pet:
      relational-persistence:
        table: pets
      attributes:
        - name: id
          type: Long
          relational-persistence:
            column: id
            primary-key: true
            autogenerated: true
        - name: name
          type: String
          relational-persistence:
            column: name
        - name: status
          type: String
          relational-persistence:
            column: status
        - name: category
          type: Relation
          ref-model: Category
          relational-persistence:
            column: categoryId
            foreign-column: id
    Category:
      relational-persistence:
        table: categories
      attributes:
        - name: id
          type: Long
          relational-persistence:
            column: id
            primary-key: true
            autogenerated: true
        - name: name
          type: String
          relational-persistence:
            column: name
  schemas:
    PetGet:
      type: object
      x-apigen-mapping:
        model: Pet
        method: get
      properties:
        id:
          type: integer
          x-apigen-mapping:
            field: id
        name:
          type: string
          x-apigen-mapping:
            field: name
        status:
          type: string
          x-apigen-mapping:
            field: status
        category:
          $ref: '#/components/schemas/Category'
    PetPost:
      type: object
      x-apigen-mapping:
        model: Pet
        method: post
      properties:
        id:
          type: integer
          x-apigen-mapping:
            field: id
        name:
          type: string
          x-apigen-mapping:
            field: name
        status:
          type: string
          x-apigen-mapping:
            field: status
        categoryId:
          type: integer
          x-apigen-mapping:
            field: category
    PetPut:
      type: object
      x-apigen-mapping:
        model: Pet
        method: put
      properties:
        id:
          type: integer
          x-apigen-mapping:
            field: id
        name:
          type: string
          x-apigen-mapping:
            field: name
        categoryId:
          type: integer
          x-apigen-mapping:
            field: category
    Category:
      type: object
      x-apigen-mapping:
        model: Category
      properties:
        id:
          type: integer
        name:
          type: string
"""


class TestResponseSchemaName:
    """ISSUE-002: response_schema_name debe venir del $ref de la respuesta, no del método."""

    def _parse_spec(self):
        parser = OpenAPIParser()
        parser.load_definition(spec_str=RESPONSE_SCHEMA_SPEC)
        parsed = parser.parse()
        return parsed

    def test_post_response_schema_is_pet_get(self):
        """POST addPet response $ref is PetGet, so response_schema_name must be PetGet."""
        parsed = self._parse_spec()
        pet_router = parsed.routers.get("pet") or parsed.routers.get("Pet")
        assert pet_router is not None, "Pet router not found"

        post_endpoint = None
        for ep in pet_router.endpoints:
            if ep.method.upper() == "POST":
                post_endpoint = ep
                break
        assert post_endpoint is not None, "POST endpoint not found"
        assert post_endpoint.response_schema_name == "PetGet", \
            f"POST response_schema_name should be 'PetGet', got '{post_endpoint.response_schema_name}'"

    def test_put_response_schema_is_pet_get(self):
        """PUT updatePet response $ref is PetGet, so response_schema_name must be PetGet."""
        parsed = self._parse_spec()
        pet_router = parsed.routers.get("pet") or parsed.routers.get("Pet")

        put_endpoint = None
        for ep in pet_router.endpoints:
            if ep.method.upper() == "PUT":
                put_endpoint = ep
                break
        assert put_endpoint is not None, "PUT endpoint not found"
        assert put_endpoint.response_schema_name == "PetGet", \
            f"PUT response_schema_name should be 'PetGet', got '{put_endpoint.response_schema_name}'"

    def test_get_response_schema_is_pet_get(self):
        """GET getPetById response $ref is PetGet, so response_schema_name must be PetGet."""
        parsed = self._parse_spec()
        pet_router = parsed.routers.get("pet") or parsed.routers.get("Pet")

        get_by_id_endpoint = None
        for ep in pet_router.endpoints:
            if ep.method.upper() == "GET" and ep.mapping and "{" in ep.mapping:
                get_by_id_endpoint = ep
                break
        assert get_by_id_endpoint is not None, "GET by id endpoint not found"
        assert get_by_id_endpoint.response_schema_name == "PetGet", \
            f"GET by id response_schema_name should be 'PetGet', got '{get_by_id_endpoint.response_schema_name}'"

    def test_post_response_attributes_exclude_fk(self):
        """POST response should use PetGet attributes (with category relation, not categoryId)."""
        parsed = self._parse_spec()
        pet_router = parsed.routers.get("pet") or parsed.routers.get("Pet")

        post_endpoint = None
        for ep in pet_router.endpoints:
            if ep.method.upper() == "POST":
                post_endpoint = ep
                break
        assert post_endpoint is not None
        assert post_endpoint.response is not None, "POST should have a response schema"

        attr_names = [a.name for a in post_endpoint.response.attributes]
        assert "category" in attr_names, \
            f"POST response should include 'category' relation, got: {attr_names}"
        assert "categoryId" not in attr_names, \
            f"POST response should NOT include 'categoryId' FK, got: {attr_names}"
