"""Tests for template generation fixes: mapper unloaded checks, DEBUG lines, Smart Mapping.

These tests verify that the parser correctly exposes persistence column names
and Smart Mapping flags, which the copier templates use to generate correct code.
"""
import pytest
from src.domain.parse_core.parsers.openapi_parser import OpenAPIParser


# Minimal OpenAPI spec with camelCase model names mapping to snake_case columns
PETSTORE_SPEC = """
openapi: 3.0.4
info:
  title: test-template-gen
  version: 1.0.0
x-apigen-project:
  name: test-template-gen
  description: test
  version: v1.0.0
  data-driver: postgresql
paths:
  /owner/{ownerId}:
    get:
      operationId: getOwner
      parameters:
        - name: ownerId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Owner'
  /address/{addressId}:
    get:
      operationId: getAddress
      parameters:
        - name: addressId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
components:
  x-apigen-models:
    Owner:
      relational-persistence:
        table: owners
      attributes:
        - name: id
          type: Long
          relational-persistence:
            column: id
            primary-key: true
            autogenerated: true
        - name: firstName
          type: String
          relational-persistence:
            column: first_name
        - name: lastName
          type: String
          relational-persistence:
            column: last_name
        - name: email
          type: String
          relational-persistence:
            column: email
    Address:
      relational-persistence:
        table: addresses
      attributes:
        - name: id
          type: Long
          relational-persistence:
            column: id
            primary-key: true
            autogenerated: true
        - name: street
          type: String
          relational-persistence:
            column: street
        - name: zipCode
          type: String
          relational-persistence:
            column: zip_code
  schemas:
    Owner:
      type: object
      x-apigen-mapping:
        model: Owner
      properties:
        id:
          type: integer
          x-apigen-mapping:
            field: id
        firstName:
          type: string
          x-apigen-mapping:
            field: firstName
        lastName:
          type: string
          x-apigen-mapping:
            field: lastName
        email:
          type: string
          x-apigen-mapping:
            field: email
    Address:
      type: object
      x-apigen-mapping:
        model: Address
      properties:
        id:
          type: integer
          x-apigen-mapping:
            field: id
        street:
          type: string
          x-apigen-mapping:
            field: street
        zipCode:
          type: string
          x-apigen-mapping:
            field: zipCode
"""


class TestMapperUnloadedCheck:
    """Verify mapper uses persistence column names in inspect(entity).unloaded checks.

    Bug: mapper.jinja was using attr.name (camelCase e.g. 'firstName') for the
    unloaded check instead of attr.persistence.column (snake_case e.g. 'first_name').
    Since inspect(entity).unloaded returns SQLAlchemy attribute names (snake_case),
    the check using camelCase never matches, causing fields to incorrectly return None.
    """

    def test_parser_provides_persistence_column(self):
        """Parser must expose persistence.column alongside attr.name for each attribute."""
        parser = OpenAPIParser()
        parser.load_definition(spec_str=PETSTORE_SPEC)
        parser.get_project()
        parser.get_entities()

        owner = parser.entities.get("Owner")
        assert owner is not None

        attr_map = {}
        for attr in owner.attributes:
            data = attr.model_dump(by_alias=True)
            persistence = data.get("relational-persistence", {})
            attr_map[attr.name] = persistence.get("column") if persistence else None

        # camelCase model name must map to snake_case DB column
        assert attr_map["firstName"] == "first_name", \
            "Parser should map firstName -> first_name column"
        assert attr_map["lastName"] == "last_name", \
            "Parser should map lastName -> last_name column"
        # Same name stays same
        assert attr_map["email"] == "email", \
            "Parser should keep email -> email column"

    def test_address_persistence_column(self):
        """zipCode should map to zip_code column."""
        parser = OpenAPIParser()
        parser.load_definition(spec_str=PETSTORE_SPEC)
        parser.get_project()
        parser.get_entities()

        address = parser.entities.get("Address")
        assert address is not None

        for attr in address.attributes:
            if attr.name == "zipCode":
                data = attr.model_dump(by_alias=True)
                col = data.get("relational-persistence", {}).get("column")
                assert col == "zip_code", \
                    "zipCode should map to zip_code column"
                return

        pytest.fail("zipCode attribute not found in Address entity")

    def test_all_attributes_have_persistence(self):
        """Every attribute must have relational-persistence with a column."""
        parser = OpenAPIParser()
        parser.load_definition(spec_str=PETSTORE_SPEC)
        parser.get_project()
        parser.get_entities()

        for entity_name, entity in parser.entities.items():
            for attr in entity.attributes:
                data = attr.model_dump(by_alias=True)
                persistence = data.get("relational-persistence")
                assert persistence is not None, \
                    f"{entity_name}.{attr.name} missing relational-persistence"
                assert persistence.get("column") is not None, \
                    f"{entity_name}.{attr.name} missing column in persistence"


# Smart Mapping spec: photoUrls defined as array in schema but String in entity
SMART_MAPPING_SPEC = """
openapi: 3.0.4
info:
  title: test-smart-mapping
  version: 1.0.0
x-apigen-project:
  name: test-smart-mapping
  description: test
  version: v1.0.0
  data-driver: postgresql
paths:
  /pet/{petId}:
    get:
      operationId: getPet
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
components:
  x-apigen-models:
    Pet:
      relational-persistence:
        table: pets
      attributes:
        - name: id
          type: Long
          relational-persistence:
            column: id
            primary-key: true
            autogenerated: true
        - name: name
          type: String
          relational-persistence:
            column: name
        - name: photoUrls
          type: String
          relational-persistence:
            column: photo_urls
  schemas:
    Pet:
      type: object
      x-apigen-mapping:
        model: Pet
      properties:
        id:
          type: integer
          x-apigen-mapping:
            field: id
        name:
          type: string
          x-apigen-mapping:
            field: name
        photoUrls:
          type: array
          items:
            type: string
          x-apigen-mapping:
            field: photoUrls
"""


class TestSmartMappingDetection:
    """Verify Smart Mapping correctly detects array-to-string type mismatches."""

    def test_smart_mapping_detected(self):
        """When schema says array but entity says String, has_json_conversion should be True."""
        parser = OpenAPIParser()
        parser.load_definition(spec_str=SMART_MAPPING_SPEC)
        parser.get_project()
        parser.get_entities()

        pet = parser.entities.get("Pet")
        assert pet is not None

        for attr in pet.attributes:
            if attr.name == "photoUrls":
                assert attr.has_json_conversion is True, \
                    "photoUrls should have has_json_conversion=True (array in schema, String in entity)"
                return

        pytest.fail("photoUrls attribute not found in Pet entity")

    def test_normal_string_no_json_conversion(self):
        """Normal string fields should not have json_conversion."""
        parser = OpenAPIParser()
        parser.load_definition(spec_str=SMART_MAPPING_SPEC)
        parser.get_project()
        parser.get_entities()

        pet = parser.entities.get("Pet")
        for attr in pet.attributes:
            if attr.name == "name":
                assert attr.has_json_conversion is False, \
                    "name is a simple String, should not have json_conversion"
                return

    def test_smart_mapping_persistence_column(self):
        """Smart Mapping field should still have correct persistence column."""
        parser = OpenAPIParser()
        parser.load_definition(spec_str=SMART_MAPPING_SPEC)
        parser.get_project()
        parser.get_entities()

        pet = parser.entities.get("Pet")
        for attr in pet.attributes:
            if attr.name == "photoUrls":
                data = attr.model_dump(by_alias=True)
                col = data.get("relational-persistence", {}).get("column")
                assert col == "photo_urls", \
                    "photoUrls should map to photo_urls column"
                return
