from pydantic import BaseModel, Field
from typing import Optional, Dict, Optional
from .openapi_structure import OpenAPIInterfaceContract, OpenAPIDomainContract
from .graphql_structure import GraphqlContract
from .asyncapi_structure import AsyncapiContract


class ProjectContract(BaseModel):
    name: str = Field(..., description="The name of the project")
    version: str = Field(..., description="The version of the project")
    description: str = Field(..., description="The description of the project")
    metadata: Optional[dict] = Field(None, description="The metadata of the project")

class EntitySchema(BaseModel):
    type: str = Field(..., description="The type of the schema")
    primary: Optional[bool] = Field(None, description="The primary key of the schema")
    autogenerated: Optional[bool] = Field(None, description="The secondary keys of the schema")

class EntityDomainContract(BaseModel):
    fields: Dict[str, EntitySchema] = Field(..., description="The fields of the entity")

class DomainContract(BaseModel):
    entities: Dict[str, EntityDomainContract] = Field(..., description="The entities of the domain")
    services: Dict[str, dict] = Field(..., description="The services of the domain")
    repositories: Dict[str, dict] = Field(..., description="The repositories of the domain")

class InterfaceContract(BaseModel):
    openapi: Optional[OpenAPIInterfaceContract] = Field(None, description="The openapi interface of the project")
    graphql: Optional[GraphqlContract] = Field(None, description="The graphql interface of the project")
    asyncapi: Optional[AsyncapiContract] = Field(None, description="The asyncapi interface of the project")

class InfrastructureContract(BaseModel):
    persistence: Dict['engine', str] = Field(..., description="The persistence of the project")
    http: Dict['baseUrl', str] = Field(..., description="The http client of the project")

class GenericStructureModel(BaseModel):
    project: ProjectContract
    domain: DomainContract
    interfaces: InterfaceContract
    contracts: OpenAPIDomainContract
    infrastructure: InfrastructureContract
    extensions: dict
