from token import OP
from pydantic import BaseModel, Field
from typing import List, Optional


class RelationalPersistence(BaseModel):
    table: Optional[str] = None
    column: Optional[str] = None
    primary_key: Optional[bool] = None
    autogenerated: Optional[bool] = None


class AttributeContract(BaseModel):
    name: str = Field(..., description="The name of the attribute")
    type: str = Field(..., description="The type of the attribute")
    items_type: str = Field(None, description="The type of the items if the attribute is a list")
    relational_persistence: Optional[RelationalPersistence] = Field(
        None, alias="relational-persistence"
    )


class ModelContract(BaseModel):
    attributes: List[AttributeContract] = Field(..., description="The attributes of the model")
    relational_persistence: Optional[RelationalPersistence] = Field(
        None, alias="relational-persistence"
    )
