import pytest

from src.domain.parse_core.parsers.asyncapi_parser import AsyncAPIParser


@pytest.fixture
def asyncapi_parser():
    return AsyncAPIParser()


@pytest.fixture
def asyncapi_definition():
    return """{
  "asyncapi": "3.0.0",
  "info": {
    "title": "Account Service",
    "version": "1.0.0",
    "description": "This service is in charge of processing user signups"
  },
  "channels": {
    "userSignedup": {
      "address": "user/signedup",
      "messages": {
        "UserSignedUp": {
          "$ref": "#/components/messages/UserSignedUp"
        }
      }
    }
  },
  "operations": {
    "sendUserSignedup": {
      "action": "send",
      "channel": {
        "$ref": "#/channels/userSignedup"
      },
      "messages": [
        {
          "$ref": "#/channels/userSignedup/messages/UserSignedUp"
        }
      ]
    }
  },
  "components": {
    "messages": {
      "UserSignedUp": {
        "payload": {
          "type": "object",
          "properties": {
            "displayName": {
              "type": "string",
              "description": "Name of the user"
            },
            "email": {
              "type": "string",
              "format": "email",
              "description": "Email of the user"
            }
          }
        }
      }
    },
    "x-apigen-models": {
      "Patient": {
        "relational-persistence": {
          "table": "patients"
        },
        "attributes": [
          {
            "name": "id",
            "type": "String",
            "relational-persistence": {
              "primary-key": true,
              "autogenerated": true
            }
          },
          {
            "name": "name",
            "type": "String",
            "validations": [
              {
                "type": "NotEmpty"
              }
            ]
          },
          {
            "name": "surname",
            "type": "String",
            "validations": [
              {
                "type": "NotEmpty"
              }
            ]
          },
          {
            "name": "stays",
            "type": "Array",
            "items-type": "Stay",
            "relational-persistence": {
              "foreign-column": "patient_id"
            }
          }
        ]
      }
    }
  },
  "x-apigen-project": {
    "name": "Account Service",
    "version": "1.0.0",
    "description": "This service is in charge of processing user signups"
  }
}
"""


def test_parse_definition(asyncapi_parser, asyncapi_definition):
    asyncapi_parser.load_definition(asyncapi_definition)
    result = asyncapi_parser.parse()
    assert result is not None
    assert hasattr(result, "project")
    assert hasattr(result, "entities")
    assert hasattr(result, "servers")
    assert hasattr(result, "channels")
    assert hasattr(result, "operations")
    assert hasattr(result, "default_content_type")
    assert hasattr(result, "components")


def test_get_operations_fallback_to_channel_messages(asyncapi_parser):
    """
    Test that if an operation doesn't define 'messages', it falls back
    to the messages defined in its channel.
    """
    asyncapi_parser.definition = {
        "operations": {
            "testOp": {
                "action": "send",
                "channel": {
                    "address": "test.topic",
                    "messages": {
                        "TestEvent": {
                            "payload": {"type": "string"}
                        }
                    }
                }
            }
        }
    }
    
    # Run the get_operations logic
    asyncapi_parser.get_operations()
    
    op = asyncapi_parser.operations.get("testOp")
    assert op is not None
    assert "messages" in op
    assert len(op["messages"]) == 1
    
    # The message should be successfully mapped from the channel
    msg = op["messages"][0]
    assert msg.get("payload") == {"type": "string"}
