from typing import Optional, Union, List, Dict
from pydantic import BaseModel, Field, ConfigDict, AliasChoices, model_validator

from src.domain.parse_core.common.enums import AttributeTypeEnum
from src.domain.parse_core.schemas.common_schema import (
    ValidationsSchema,
)

_KNOWN_TYPES = {
    "Array", "String", "Boolean", "Double", "Float", "BigDecimal",
    "Integer", "Long", "BigInteger", "LocalDate", "LocalDateTime",
    "ZonedDateTime", "OffsetDateTime", "Instant", "Relation", "ComposedID",
    "Date", "DateTime", "Int", "UUID", "Numeric", "Number", "Text",
    "Byte", "Binary", "Password", "Email", "Uri", "Url",
    "string", "integer", "boolean", "number", "object", "array",
}
_KNOWN_TYPES_LOWER = {t.lower() for t in _KNOWN_TYPES}


class EntityAttrubuteColumnProperties(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    column: Optional[str] = None
    primary_key: bool = Field(alias="primary-key", default=False)
    unique: bool = Field(default=False)
    autogenerated: bool = Field(alias="autogenerated", default=False)
    sequence: Optional[str] = None
    foreign_column: Optional[str] = Field(
        alias="foreign-column", default=None
    )
    columns: Optional[Dict[str, str]] = None
    foreign_columns: Optional[Dict[str, str]] = Field(
        default=None, alias="foreign-columns"
    )
    join_table: Optional[str] = Field(
        default=None,
        validation_alias=AliasChoices("join-table", "intermediate-table", "intermediary-table"),
    )
    join_column: Optional[str] = Field(
        alias="join-column", default=None
    )
    inverse_join_column: Optional[str] = Field(
        alias="inverse-join-column", default=None
    )
    relation_type: Optional[str] = Field(
        alias="relation-type", default=None
    )
    owner: Optional[bool] = None
    reverse_relation: Optional[str] = Field(
        alias="reverse-relation", default=None
    )

    validations: Optional[list[ValidationsSchema]] = None


class EntityAttribute(BaseModel):
    name: str
    type: Union[str, AttributeTypeEnum]
    is_array: bool = Field(default=False, validation_alias=AliasChoices("is-array", "is-collection"), serialization_alias="is-array")
    items_type: Optional[str] = Field(alias="items-type", default=None)
    items_ref_model: Optional[str] = Field(alias="items-ref-model", default=None)
    ref_model: Optional[str] = Field(alias="ref-model", default=None)
    has_json_conversion: bool = Field(default=False)
    is_exposed_in_schema: bool = Field(default=False)
    read_only: bool = Field(default=False)
    write_only: bool = Field(default=False)
    column_properties: Optional[EntityAttrubuteColumnProperties] = Field(
        alias="relational-persistence", default=None
    )
    attributes: Optional[List['EntityAttribute']] = None

    model_config = ConfigDict(use_enum_values=True, populate_by_name=True)

    @model_validator(mode='after')
    def _normalize_springboot_style(self):
        type_str = self.type if isinstance(self.type, str) else self.type.value

        if type_str == "Array" and not self.is_array:
            self.is_array = True

        if type_str.lower() not in _KNOWN_TYPES_LOWER and not self.is_array:
            if not self.ref_model:
                self.ref_model = type_str
            self.type = "Relation"

        if self.is_array and self.items_type and self.items_type.lower() not in _KNOWN_TYPES_LOWER:
            if not self.items_ref_model:
                self.items_ref_model = self.items_type

        if self.is_array and self.ref_model and not self.items_ref_model:
            self.items_ref_model = self.ref_model

        return self


class EntitySchema(BaseModel):
    table: str
    attributes: list[EntityAttribute]
